#+title: Topico 101.1 Determinar e definir configurações de hardware
#+author: Gabriel
#+description: Identificar dispositivos de hardware

* #1 Determinar e definir configurações de hardware (/proc, /sys, /dev)

- O sistema de arquivo sysfs é descrito como a união dos sistemas de arquivo proc, devfs e devpty.

O sistema de arquivo sysfs enumera os dispositivos e canais conectados ao sistema numa hierarquia de sistema de arquivo que pode ser acessada pelo espaço do usuário

É montado em /sys/ e contém directorys organizando os dispositivos conectados ao sistema de diversas maneiras diferentes. Dentro do dir /sys podemos encontrar quase o mesmo conteúdo do proc, mas de uma forma bem mais organizada.

Tratando-se de dispositivos, outro dir muito importante é o */dev*. Nele encontramos arquivos especiais que representam a maioria dos dispositivos do sistema, particulamente dispositivos de armazenamento.

Um disco conectado a uma controladora IDE por exemplo, quando conectado ao primeiro canal IDE de placa mãe, é reprsentado pelo arquivo de dispositivo */dev/hda* ou */dev/sda*. Cada partição deste disco será identificada como */dev/sda1*, */dev/sda2* e até a ultima partição encontrada..

* #2 Determinar e definir configurações de hardware (DMA, IRQ, I/O, SCSI)

O directory */proc* contém vários arquivos especiais que representam desde processos em execução até detalhes de dispositivos conectados ao servidor.

  O admin poderá consultar os arquivos deste directory para obter mais informações sobre o system.
  Pode-se utilizar o comando *cat* para listar o content destes arquivos no directory, entre eles vale destacar os seguintes arquivos ->

**** /proc/cpuinfo
-> Apresenta informações sobre a CPU, quantidade de nucleos, velocidade, uso em geral etc...
**** /proc/interrupts
-> Contém informações sobre as requisições de interrupções (IRQ) nos processadores, requests para os processadores e sua prioridade
**** /proc/ioports
-> Exibe os endereçõs de E/S que estão sendo utilizados na memória e os dispositivos que estão utilizando estes endereçs
**** /proc/meminfo
-> Informações sobre a quantidade de memória total, memória em uso, cache etc...
**** /proc/dma
-> Contém informações sobre o canal de acesso direto a memória(DMA) usado por dispositivos conectados ao computador.

** cat

#+begin_src sh
cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 42
model name	: Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz
stepping	: 7
microcode	: 0x2f
cpu MHz		: 2494.249
cache size	: 6144 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
#+end_src


#+begin_src sh
cat /proc/meminfo

MemTotal:       16269784 kB
MemFree:         1282432 kB
MemAvailable:   11600092 kB
Buffers:         1475680 kB
Cached:          7529972 kB
SwapCached:            0 kB
Active:          7362348 kB
Inactive:        5062652 kB
Active(anon):    3688424 kB
Inactive(anon):        0
#+end_src

#+begin_src sh
cat /proc/interrupts

           CPU0       CPU1       CPU2       CPU3
  0:         51          0          0          0  IR-IO-APIC   2-edge      timer
  8:          0          0          0          0  IR-IO-APIC   8-edge      rtc0
  9:          0          3          0          0  IR-IO-APIC   9-fasteoi   acpi
 16:          0         25          0          0  IR-IO-APIC  16-fasteoi   ehci_hcd:usb2
 18:          0          5          0          0  IR-IO-APIC  18-fasteoi   i801_smbus
 23:       9851          0        102          0  IR-IO-APIC  23-fasteoi   ehci_hcd:usb1
 24:          0          0          0          0  DMAR-MSI   0-edge      dmar0
 25:          0          0          0          0  DMAR-MSI   1-edge      dmar1
 26:          0          0      88550          0  IR-PCI-MSI-0000:00:1f.2   0-edge      ahci[0000:00:1f.2]
#+end_src

#+begin_src sh
cat /proc/ioports

0000-0000 : PCI Bus 0000:00
  0000-0000 : dma1
  0000-0000 : pic1
  0000-0000 : timer0
  0000-0000 : timer1
  0000-0000 : keyboard
  0000-0000 : keyboard
  0000-0000 : rtc0
  0000-0000 : dma page reg
  0000-0000 : pic2
#+end_src

#+begin_src sh
cat /proc/dma

 4: cascade
#+end_src

* #3 Identificar dispositivos IDE, SATA e SCSI

Os dispositivos SCSI possuem algumas particularidades em relação a outros dispositivos de *armazenamento*

Dois principais tipos de dispositivos SCSI :

 * 8 bits que podem conectar 7 dispositivos *(disks/devices)* e a controloadora

 * 16 bits que podem conectar 16 dispositivos *(disks/devices)* e a controladora

#+begin_src sh
cat /proc/scsi/scsi

Attached devices:
Host: scsi4 Channel: 00 Id: 00 Lun: 00
  Vendor: ATA      Model: STT256I1-2YAMCG2 Rev: AA10
  Type:   Direct-Access                    ANSI  SCSI revision: 05
#+end_src

#+begin_src sh
cat /proc/scsi/device_info

'TOSHIBA' 'CD-ROM' 0x100
'Traxdata' 'CDR4120' 0x1
'USB2.0' 'SMARTMEDIA/XD' 0x402
'WangDAT' 'Model 2600' 0x200000
'WangDAT' 'Model 3200' 0x200000
'WangDAT' 'Model 1300' 0x200000
'WDC WD25' '00JB-00FUA0' 0x40000
'XYRATEX' 'RS' 0x240
'Zzyzx' 'RocketStor 500S' 0x40
'eZzyzx' 'RocketStor 2000' 0x40
#+end_src

Os hds/ssds são reconhecidos como sd (alphabetic character) 1 de acordo com suas partições existentes ->

 * sda1
 * sda2
 * sdb1
 * sdb2

Dispositivos de leitores de DVD por exemplo são conhecidos como, utilizando o driver *cdroom*
 * sdr1
 * sdr2


 Dependendo de qual controladora os discos estão a nomenclatura deles será diferente, caso sejam 2 na primeira controladora, será */dev/sda* e */dev/sdb*

 Caso estejam na segunda controladora, serão nomeados como */dev/sdc* e */dev/sdd*

* #4 Determinar e definir configurações de hardware (lspci, lsusb, lsmod)

 * O comando *lspci* exibe componentes conectados ao barramento PCI, como:

   * Controladores de disco
   * Placas de rede
   * Placas de vídeo
    *  Controladoras USB

#+begin_src sh
00:00.0 Host bridge: Intel Corporation 2nd Generation Core Processor Family DRAM Controller (rev 09)
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
00:16.0 Communication controller: Intel Corporation 6 Series/C200 Series Chipset Family MEI Controller #1 (rev 04)
00:1a.0 USB controller: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #2 (rev 05)
00:1b.0 Audio device: Intel Corporation 6 Series/C200 Series Chipset Family High Definition Audio Controller (rev 05)
00:1c.0 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 1 (rev b5)
00:1c.4 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 5 (rev b5)
00:1d.0 USB controller: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #1 (rev 05)
00:1f.0 ISA bridge: Intel Corporation H61 Express Chipset LPC Controller (rev 05)
00:1f.2 SATA controller: Intel Corporation 6 Series/C200 Series Chipset Family 6 port Desktop SATA AHCI Controller (rev 05)
#+end_src


 * O comando *lsusb* exibe dispositivos conectados nas portas USB da máquina

 #+begin_src shell
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 003: ID 10c4:8108 Silicon Labs USB OPTICAL MOUSE
Bus 001 Device 004: ID 320f:5000 Evision RGB Keyboard
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
 #+end_src

 * O comando *lsmod* exibe os módulos carregados em memória ->

 #+begin_src sh
Module                  Size  Used by
tcp_diag               12288  0
udp_diag               12288  0
inet_diag              28672  2 tcp_diag,udp_diag
nf_conntrack_netlink    57344  0
xt_nat                 12288  11
veth                   45056  0
xt_set                 20480  0
ip_set                 61440  1 xt_set
xfrm_user              61440  1
 #+end_src
