#+title: Systemd | Inicialização do sistema
#+author:Gabriel

* systemd
 É um gerenciador de sistema e serviços para sistemas operacionais Linux. Podendo ser executado como um sistema init para inicializar o sistema também.

Ele foi projetado para ser compatível com os scripts de incialização SysVinit e fornece uma séria de recursos.

 - Inialização paralela de serviços no sistema

- Ativação sob demanda de daemons

- O systemd monitora processos usando o ~cgroups~ do Linux, garantido que ao parar um determinado serviço, todos os processos que tenham sido iniciados por ele sejam finalizados

- Implementa uma lógica de controle de serviço baseado em dependências.

  Geralmente seu principal dir está em */lib/systemd/system*, em distros red hat podem estar em */usr/lib/systemd/system*

* unidades
O systemd inicializa e supervisiona todo o sistema e é baseado no conceito de unidades. Uma unidade é composta por um nome e um tipo e possui um arquivo de configuração correspondente.

=Tipos de unidades SystemD:=

*** service
O tipo mais comum, onde serviços podem ser iniciados, interrompidos, reiniciados e recarregados.

*** socket
Esse tipo de unidade pode ser um socket no sistema de arquivos ou na rede, cada unidade do tipo socket possui uma unidade do tipo service correspondente, que é iniciada somente quando uma conexão chega à unidade socket.

*** device
Uma unidade para um dispositivo presente na árvore de dispositivos Linux. Um dispositivo é exposto como unidade do systemd se houver uma regra do udev com essa finalidade

*** target
Unidade especial pois trata-se de um agrupamento de unidades, de forma que sejam controladas em conjunto. Parecido com os níveis de execução do SysVinit

*** mount
Uma unidade que é responsável por um ponto de montagem no sistema de arquivos
