#+title: SysVinit
#+AUTHOR: Gabriel FErreira

* SysVinit
É um sistema de inicialização usado em muitas distribuições GNU/Linux por default. Ele é o primeiro processo que é iniciado após o carregamento do kernel, portanto recebe o primeiro PID chamado *init*

O sysvinit sempre inicia os processos em uma ordem predeterminada, e inicia uma processo normalmente apenas quando o processo anterior foi concluído. Ele não trabalha com paralelização de processos, igual ao systemd.

O sysvinit trabalha com níveis de inicialização, os chamados "runleves" para iniciarem os serviços do sistema.

Geralmente seu principal dir é */etc/init.d* , no Debian 5 por exemplo, que ainda usava o SysVinit. Este dir vai conter os daemnos do processo INIT, sendo que existem links simbólicos para os dirs rc1, rc2 etc...

Geralmente os Runleves estão localizados no Debian 5 como ->
 * /etc/rc1.d
 * /etc/rc2.d
 * /etc/rc3.d

Em distros *Red Hat* o padrão muda um pouco, os diretórios rc*.d e init.d ficam como subdiretórios em */etc/rc.d*

O diretório para scripts de gerenciamento dos serviços do sistema é o */etc/rc.d/init.d em *Red Hats* o link simbólico */etc/init.d aponta para o dir /etc/rc.d/init.d*

* Arquivo /etc/inittab

O arquivo em que se define o runlevel padrão da inicialização é o /etc/inittab.

Neste arquivo se configura em qual nível o sistema vai ser inicia, manuntenção, single user etc...

*** Debian

 * *0* -> shutdown

 * *1,s,S* -> Single mode(recovery ?), only root can access

 * *2 - 5* -> Multiuser, graphical and text modes

 * *6* -> Reboot

*** Red Hat

 * *0* -> shutdown

 * *1,s,S* -> Single mode, only root can access that mode

 * *2* -> Multiuser without share files NFS (without network)

 * *3* -> Multiuser with network and text mode

 * *4* -> Not usable, but customizable

 * *5* -> Complete multiuser with graphical (default)

 * *6* -> Used to reboot

** Centos 6 /etc/inittab

#+begin_src bash
[root@centos6-lpic1 ~]# cat /etc/inittab
# inittab is only used by upstart for the default runlevel.
#
# ADDING OTHER CONFIGURATION HERE WILL HAVE NO EFFECT ON YOUR SYSTEM.
#
# System initialization is started by /etc/init/rcS.conf
#
# Individual runlevels are started by /etc/init/rc.conf
#
# Ctrl-Alt-Delete is handled by /etc/init/control-alt-delete.conf
#
# Terminal gettys are handled by /etc/init/tty.conf and /etc/init/serial.conf,
# with configuration in /etc/sysconfig/init.
#
# For information on how to write upstart event handlers, or how
# upstart works, see init(5), init(8), and initctl(8).
#
# Default runlevel. The runlevels used are:
#   0 - halt (Do NOT set initdefault to this)
#   1 - Single user mode
#   2 - Multiuser, without NFS (The same as 3, if you do not have networking)
#   3 - Full multiuser mode
#   4 - unused
#   5 - X11
#   6 - reboot (Do NOT set initdefault to this)
#
id:5:initdefault:
#+end_src


Trocar de runlevel com *telinit* ->
#+begin_src bash



#+end_src
