#+title: Basics
#+author:gabriel

** Shell Scripting
Shell scripts are sequences of shell commands collected in a file and executed with a single command. This is particularly useful for automating repetitive tasks and simplifying processes.

Instead of writing the same command sequence repeatedly, you can easily manage the entire process with a shell script.

Shell scripts have a structure similar to other programming languages and include the following elements:

- Shell Keywords: Includes structures like if, else, break.
- Shell Commands: Uses basic Unix/Linux commands like cd, ls, echo, pwd, touch.
- Functions: Groups repeated code blocks functionally.
- Control Flow Structures: Includes structures like if..then..else, case, and loops.

#+begin_src bash simple example
#!/bin/bash

# comment

echo "Hello, World!"
#+end_src

*#!/bin/bash* ->
This is the shebang line. It specifies which shell interpreter should be used to run the script. It tells the system that this script should be executed with bash.

*# comment* ->
This line is a comment, and comment lines start with the # symbol. Comments are ignored by the bash interpreter and are used to explain what the script or code does.

*** Multi-Line comments
In some cases, your explanation may need to span multiple lines. Multi-line comments are used for such situations. In shell scripting, multi-line comments start with : ' and end with '.

#+begin_src bash
: '
This is a multi-line comment
Each line will be treated as a comment
'
#+end_src

*** Variables
In shell scripting, we use variable structures to store and manage data. Unlike some programming languages, you do not need to specify the type of a variable before using it

*System-Defined Variables* ->
These variables are defined by the system itself and are usually written in uppercase letters. They are also known as environment variables and contain important information about the system.

 For example, you can view all available environment variables using the ~printenv~ command.

*User-Defined variables* ->
These variables are created by the user writing the script and only exist for the duration the code is executed.

To define a variable, write the variable name and assign it a value using the = sign. To access a variable, prefix the variable name with the $ sign.

#+begin_src bash
#!/bin/bash

# Accessing an Environment Variable
echo $PATH

# Defining a variable
name="Alex"
number=19

echo $name
echo "Number: $number"
#+end_src

When writing scripts, you may often need to compare the values of variables. Basic comparison operators you can use in shell scripting:


*Integer Comparison* ->
| Operator | Description
| -eq | Checks if two variables are equal.
| -ne | Checks if two variables are not equal.
| -gt | Checks if the variable on the left is greater than the variable on the right.
| -ge | Checks if the variable on the left is greater than or equal to the variable on the right.
| -lt | Checks if the variable on the left is less than the variable on the right.
| -le | Checks if the variable on the left is less than or equal to the variable on the right.

*String Comparison* ->
| Operator | Description
| == | Checks if two strings are equal.
| != | Checks if two strings are not equal.
| < | Checks if one string is less than another string in alphabetical order.
| > | Checks if one string is greater than another string in alphabetical order.

Remember that when using < and > operators, these characters may be specially recognized by the shell. Therefore, when used within the [ ] structure, they should be prefixed with the escape character \.

*** Conditional Statements
Conditional statements allow you to execute specific code blocks if certain conditions are met. Shell scripting supports such conditional statements and allows you to check conditions through comparison operators.

*IF* ->
#+begin_src bash
#!/bin/bash

a=10
b=10
if [ $a -eq $b ]
then
    echo "Equal"
fi
#+end_src

Note: When using conditional statements, remember to leave a space before and after the condition within the brackets [ ]. Otherwise, you may encounter an error when running the script.

*** Loops
Loops are structural commands that allow a set of commands to be executed repeatedly until a certain condition is met. Various loop structures can be used in shell scripts

*While Loop* ->
A while loop executes the specified commands as long as the condition is true. The loop ends when the condition is false.
#+begin_src sh while example
#!/bin/bash

number=1
while [ $number -lt 5 ]
do
    echo $number
    number=`expr $number + 1`
done
#+end_src

*For Loop* ->
A for loop allows a variable to iterate over a list of values or a range of values.
#+begin_src bash
#!/bin/bash

for number in 4 8 12 20 25 30
do
echo $number
done
#+end_src




https://e2.udemymail.com/ls/click?upn=u001.TtzRjPf63yUg9yrAxgqE78WDKTn6A2iSo8JCeA5RUg9mgZFkMRcnxg9jeHS7UNmy4luiLLRMH5BPaHNcP73JzO3UseoPalYgQnNekrCcETa-2BHUqy35pL8LvBDs3g5LouxeInQVM9wO4uVo-2F7vdBl9oK6Mfx3bS8s8FAL-2FwUzWzmRf66A1js93SBIiW2pkvuVRS5Y35f3qUZZrgzNX5HSW6nGTLuIoX-2B-2FhZxAHmH-2F-2Bv5WQhHJ3OVF8cW3cgol0nWtweq7A9Fn6QdeYhwUcKbeO9iWszTXdomEHwDF7tFcEbVFYOPQXuHY4tRQexR8aHr8xrHm_a4aWiUrIrQ0LCpE9WVsWlvFFlMTfJhw-2Byi5H2OgSKj4TMTkEKqCp7kDk0KdAWpHTsxD4qUrYkkefMA7I8vSrJp3QdHXqBy9izZm-2FId1pDFMGty3eBcsa3LPgYXeLn3lMyzKn9hL1cb9ErmOIn9AAEMmHwDjxcbTHDyqmpnQ-2BxQuDhDF9ee7mKNmHs9M6UyAXyhMLDgUv6in7P-2BB01vlJjjrdcd3doiCn0AvktfimlobUggRJDinSyt7otAIfhNZ9ykvb24E39AwlkHRCshjDkHFJFLHNAO1ZlS3Fk-2FVHEVS1rEQrxPV-2B2ehtK5lj9wALqOAAVgPXLSwN4XSUtCtmgPlmJchj4CVTanMTN8T-2BFez8nZnbw5O-2BTw7jQEIzVWBYSSFkhOV9XKIVJFRYiGrtjgOdvr-2B8YKNZJgimqXio2XG5FYK7OR7csT2lHO9qsQos5k6FK7c5Q2uAfBYbLGS5GwJrudmYz06PzueYaPVTD-2FLpkhiAz7Z38Dk7gdUHKny-2B0nhCe4Yjjd-2BESZdHcV-2FYEw-3D-3D
